# Generated by Django 5.0.7 on 2024-07-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('mobile', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
