# Generated by Django 5.0.7 on 2024-07-20 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redis_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesdata',
            name='mobile',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
